### ISSUE TITLE
Whitelist activating in DMs.

### ISSUE THREAD

**Issue by imaaronburns** [pastorhudson/pcobot#108]
When using a command like !email or !birthday in my DM with our PCO Bot, it always gives me the following response:

- I might have that email address. I'll look. (Good!)
- The "Dd6B1Ncpn" channel is not whitelisted. So I sent it as a direct message. (Bad.)
- Here you go: {the info I requested.} (Good!)

Basically, it's flagging my DM channel as not being in the whitelist, though DMs should be automatically whitelisted.

![screen shot 2018-10-18 at 2 19 32 pm](https://user-images.githubusercontent.com/4576711/47175369-ef0e5000-d2e0-11e8-8c44-412f51df744a.png)

**Comment by pastorhudson** [comment]
I think #114 is a fix for this. Let me know after it's deployed.

**Comment by pastorhudson** [comment]
I found this bug again. Hopefully #121 fixes it

**Comment by pastorhudson** [comment]
I think this is fixed so closing this one. If it's not working please reopen.
