### ISSUE TITLE
Add Active/Inactive filter for Birthday Announcement

### ISSUE THREAD

**Issue by davidamann** [pastorhudson/pcobot#127]
Ability to toggle birthday announcement to active profiles only (or perhaps even toggle by individual statuses?).

**Comment by pastorhudson** [comment]
I just pushed a fix for this in #126 🎉

**Comment by pastorhudson** [comment]
The fix was to just filter all inactive profiles from the birthday announcement. I think this makes the most sense.

**Comment by davidamann** [comment]
Great! Thanks! I agree that makes the most sense!
