### ISSUE TITLE
Names containing 'and' are truncated

### ISSUE THREAD

**Issue by krouppa** [pastorhudson/pcobot#146]
When searching for information a person with a name containing **_and_**, e.g. Brandon, or Randy, PCObot will truncate at the **_and_** and only search for the characters before that. For example, **Brandon Smith** would be sent to Planning Center as **Br**, and **Alford Brandon** would be sent to Planning Center as **Alford Br**.

**Comment by pastorhudson** [comment]
Oh interesting. Any ideas what’s going on?

**Comment by pastorhudson** [comment]
Can you check if this is only happening for phone number?

**Comment by pastorhudson** [comment]
I pushed a fix for this in #149 thank you for opening an issue!
