### ISSUE TITLE
Bot should send list of birthdays on that day every day.

### ISSUE THREAD

**Issue by pastorhudson** [pastorhudson/pcobot#15]
Bot should send list of birthdays to birthday channel.

**Comment by Chalta** [comment]
To implement this, I think it would make sense to add a "today's birthday" function to [birthday.py](https://github.com/pastorhudson/pcobot/blob/master/plugins/pco/birthday.py).  (with an optional `@respond_to`.)

Then we can just call it from announcements.py

**Comment by pastorhudson** [comment]
Ya that should be easy enough

**Comment by Chalta** [comment]
Can be closed!

**Comment by pastorhudson** [comment]
Woohoo!
