### ISSUE TITLE
App fails to install on Heroku because of unsupported python-3.6.6 version

### ISSUE THREAD

**Issue by pixelstuff** [pastorhudson/pcobot#156]
When trying to install to Heroku (brand new account) there is an error message saying:

- Requested runtime (python-3.6.6) is not available for this stack (heroku-20). 

Heroku says the default version as of today is 3.6.12.

This is a confusing error since [back in 2019 you posted a message](https://github.com/pastorhudson/pcobot/releases/tag/pcobot-python-27-35) saying only python-3.7 and newer would be supported. Why would the app be requesting python-3.6.6 at install? More importantly, what is the best way to install the app on Heroku?

**Comment by pastorhudson** [comment]
That's a good question. I'll have to dig into the build pack. This will probably die Feb 24 when the slack api it's build upon dies. I'm waiting to see if there is support to update it.

**Comment by pastorhudson** [comment]
@pixelstuff I'm updating the heroku runtime. It was indeed the wrong version of python. I'll comment back if the fix works.

**Comment by pastorhudson** [comment]
It now builds on heroku again. The heroku build has been updated to python 3.9.1 and other packages have been updated to work with python 3.9.1.

NOTE: You can not generate the Slack Legacy Token needed to run this anymore. It only works if you already have the token from before. They will be killing the slack api this uses Feb 24 2021.

I'm looking at rewriting the slack backend to make it keep working, but it's a considerable effort.
