### ISSUE TITLE
Alpine Linux doesn't respect strftime('%B %-d, %Y')

### ISSUE THREAD

**Issue by pastorhudson** [pastorhudson/pcobot#21]
The checkin function relies on `datetime.strftime()` specifically the %-d option that strips the zeros off the front of a day in the format July 02, 2018 `strftime('%B %-d, %Y')` makes it July 2, 2018. This is necessary to match with planning center's date format.

Alpine linux which is what the docker images are based on doesn't respect %-d. So we either need a different distro in the docker image or a workaround.

I considered `.lsstrip('0'` but this is going to break July 20, 2018 and make it July 2, 2018.

**Comment by Chalta** [comment]
```strftime('%d').lstrip('0')```

Works for me. 20 is ```20``` and 02 is ```2```.

**Comment by pastorhudson** [comment]
It must be something else with Alpine maybe the timezone issue. But no date prints when I run the !checkin command on a bot running in the docker image.

**Comment by pastorhudson** [comment]
It was services !setlist that relied on the specific format.

```
last_checkin = last_checkin.strftime('%B %-d, %Y').lstrip('0')  # linux
                        print(last_checkin)
```
This works find on most distros, but on Alpine it just makes last_checkin blank.
I just removed the - in %-d. This solves it for checkin.
