### ISSUE TITLE
Redis listed twice in requirements.txt and subfiles

### ISSUE THREAD

**Issue by Chalta** [pastorhudson/pcobot#22]
```Double requirement given: redis==2.10.6 (from -r will/requirements/base.txt (line 24)) (already in redis==2.10.6 (from -r requirements.txt (line 2)), name='redis')```

**Comment by pastorhudson** [comment]
Hmm I wonder if there's some reason for this or if it's just an oversite from the will bot.

**Comment by Chalta** [comment]
It seems the problem only happens if running ```pip install -r requirements.txt``` with sudo permissions?

**Comment by pastorhudson** [comment]
I removed the line from requirements.txt. Let’s see if that works.
