### ISSUE TITLE
PCO API Application Key not checked in start_dev_will.py

### ISSUE THREAD

**Issue by Chalta** [pastorhudson/pcobot#23]
Slack Token and PCO Secret is checked for, but not PCO Application.

**Comment by pastorhudson** [comment]
Great catch!

**Comment by pastorhudson** [comment]
It does check for the API keys in environment. It just checks in a different place than the Slack Key.

![image](https://user-images.githubusercontent.com/3606628/42771323-d3ff0416-88f4-11e8-8442-3e4104ef34cc.png)
