### ISSUE TITLE
Flake8 CI Checks

### ISSUE THREAD

**Issue by Chalta** [pastorhudson/pcobot#27]
I don't have the bot fully up and running yet. The WILL_PCO_API_SECRET has been giving me some grief. 

Once I'm up and running on that front, I'll try to find time to go through the PCO plugin files and get them PEP8 compatible - pretty sure that's why the CI is failing on pull requests.

I'll run them through the code inspection of my IDE.

**Comment by pastorhudson** [comment]
I don’t think there’s that many pep8 issues on the pco plugin, but pypco has a bunch of pep8 errors. I use PyCharm and try to fix all the squiggly lines I see in my code. 😂

Would it be helpful to make a slack channel? I’m on planning center slack you could dm me. Maybe I can help with getting you running?

**Comment by pastorhudson** [comment]
I think Travis is failing because it's trying Python 2.7.14. You need 3.5 or better.

**Comment by Chalta** [comment]
Ah, you could be right. I know Python 3 was controversial, but there's no good reason not to code for it.

**Comment by pastorhudson** [comment]
I'm new to python. I never used 2.anything so I'm good with just moving forward with the latest 3.7 etc.

**Comment by pastorhudson** [comment]
Pypco is passing too just not in python 2.7
