### ISSUE TITLE
Move pypco from build and pull from git.

### ISSUE THREAD

**Issue by pastorhudson** [pastorhudson/pcobot#28]
I have made pull requests to https://github.com/billdeitrick/pypco/pulls/pastorhudson but Bill wants to make api discovery automatic rather than using the endpoints I added in manually. Pcobot needs to use my version of pypco so it can access the endpints. Durring early dev I just put it in the same directory. Now that I'm working on the docker build I want this cleaner and more modular. So I'll be removing the pypco folder and instead pulling it from github.com/pastorhudson/pypco.git. I'll leave this open until travis, and docker are working with this solution.

**Comment by Chalta** [comment]
Should we clean up (PEP8) the code in your fork, then PR it back to Bill?

**Comment by pastorhudson** [comment]
Yes to both. I think Bill is right. His solution will be better in the long run. I just didn't want to wait for that to build pcobot. So the build will pull both pcobot, and pypco from my repository for now. And pypco from Bill's if that project progresses in the future. I already have this working in docker. 

```
# This is edited to pull the pcobot from github rather than will bot.
# This is the docker file pastorhudson/pcobot is built on.
# It still runs on the will-base image.

#Pull from will-base
FROM heywill/will-base:3.7-alpine
ARG repo=https://github.com/pastorhudson/pcobot.git
ARG branch=master
ARG backends="Slack"
ENV PACKAGES="\
  dumb-init \
  bash \
  ca-certificates \
  python2 \
  py-setuptools \
  libffi-dev \
"
# Maintainer
# ----------
LABEL maintainer=mlove@columnit.com 

RUN pip install git+https://github.com/pastorhudson/pcobot.git@$branch 
RUN pip install git+https://github.com/pastorhudson/pypco.git
WORKDIR $_WILL_HOME
RUN generate_will_project  --backends $backends
CMD $_WILL_HOME/run_will.py
```

This is what pastorhudson/pcobot:alpha is built on.
And I've uploaded a docker-compose that is currently working too. 

We will need to update the manual install instructions for just running pure python.

I welcome a pull request to fix pep8 in my fork of pypco, Bill might too.

**Comment by pastorhudson** [comment]
I'm ready to pull pypco out of this repositoy.

**Comment by pastorhudson** [comment]
Done! seems to be working.
