### ISSUE TITLE
Channel whitelist for sensitive information

### ISSUE THREAD

**Issue by Chalta** [pastorhudson/pcobot#29]
Pcobot should not post sensitive information in public channels from :lock: restricted commands.

A whitelist could be implemented (editable by users from within Slack) that would only reply with sensitive information if the channel is in the whitelist (e.g. #pastoral-care, #scheduling). Otherwise, pcobot would reply to the requesting user:

```I've found what you were looking for, but this channel is not approved for posting private information. Instead, I've sent you that information by direct message. You can add this channel to the private information whitelist with the !xxx command.```

The command to add channels to the whitelist should perhaps have some prompts to ensure it is not misused. 

:warning: This will allow requested private information to be visible to all users of this channel. Are you sure? Yes  | No

**Comment by pastorhudson** [comment]
This will probably need to use the willbot acl system. I haven't been able to get specific user role permissions just whether they have access or not. I would be more elegant if we could restrict the ability to whitelist channels to managers or editors in Planning Center

**Comment by Chalta** [comment]
I'm okay with that. Once this is up and running, perhaps some of the commands can be switched to `@ hear` instead of `@respond` so that will can volunteer certain information when relevant.

**Comment by pastorhudson** [comment]
I like having it @hear but my team complained that it was too noisy. . .
Also, there are false positives because regex is never foolproof.

**Comment by pastorhudson** [comment]
This is almost ready to commit. I just have some cleanup stuff, and figuring out how to set whitelist on commands.

**Comment by pastorhudson** [comment]
Ok this is working in dev! Pulling it into master if everything checks out!

**Comment by pastorhudson** [comment]
Whitelist is implemented! I didn't get to do the post confirmation, but maybe we can come back to that as an enhancement.
