### ISSUE TITLE
Will homepage breaks under Python 3.6

### ISSUE THREAD

**Issue by Chalta** [pastorhudson/pcobot#45]
The smiling will head works fine under python-2.7.15

Breaks under python 3.6.3 (Heroku stack 16)

```
Error: 404 Not Found
Sorry, the requested URL 'https://||||||||||.herokuapp.com/' caused an error:

Not found: '/'
```
What's strange is that /ping and /keep-alive seem to work.

**Comment by Chalta** [comment]
I suspect this may also be related to the fact that will doesn't boot up into a prompt in the shell after running start.sh. One is potentially causal of the other, or they likely share a common root cause in python 3.

At least on my (now successful) install, will hangs right after starting scheduling and doesn't get to the 

```you: ``` 

prompt.

**Comment by pastorhudson** [comment]
The heroku build isn’t using start.sh
And we don’t get a You: prompt because I disabled shell in the config.py I didn’t see it as necessary on a docker or heroku build. That shouldn’t mess up the webpage.

**Comment by Chalta** [comment]
Is the you prompt disabled on vanilla python builds?

**Comment by Chalta** [comment]
The web plugin was disabled.

**Comment by pastorhudson** [comment]
Currently yes. But that could be changed.

**Comment by Chalta** [comment]
Fixed with https://github.com/pastorhudson/pcobot/pull/51

**Comment by pastorhudson** [comment]
Beautiful!
