### ISSUE TITLE
Intruder alerts

### ISSUE THREAD

**Issue by Chalta** [pastorhudson/pcobot#59]
Perhaps the bot should notify if a user joins who can not be matched to a pco "People" entry.

**Comment by pastorhudson** [comment]
Lol that would be funny
Ron Hudson Jr.
Lead Pastor
Calvary Baptist Church
Uniontown PA 15401

**Comment by pastorhudson** [comment]
It wouldn't be a bad idea to DM that person.

**Comment by Chalta** [comment]
I'm thinking in the scenario when a church's slack is set to allow other users to invite new users - how do we ensure that the new users actually have a relationship to the church? By matching them to an entity in People. Two things are either true:

- The new user doesn't have a People entry (and should)
- They don't belong here and should be kicked

Either case should be brought to the attention of administrators.

**Comment by pastorhudson** [comment]
Hmm I see so you mean more of a notify an "admin". I saw "@on join" was proposed for will. Not sure it was implemented. We'd need that hook for this to work.

**Comment by Chalta** [comment]
I've seen references to roster before. Perhaps a regular check or scheduled announcement, to ensure that users who are removed in People are also removed in Slack. Just to keep things tidy.

**Comment by pastorhudson** [comment]
Ya we could check slack_people_cache I guess.

**Comment by pastorhudson** [comment]
I'm cleaning up issues, I think this one is out of scope for now. Feel free to reopen if you're seeing it as an issue in teams.
