### ISSUE TITLE
Help fixes

### ISSUE THREAD

**Issue by pastorhudson** [pastorhudson/pcobot#70]
When my pcobot responds it tells me to `@cbc help` but my will handle is set to @cbcbot.

**Comment by Chalta** [comment]
Did a little bit of testing and this is a problem with the slack IO adapter in the backend plugin.

The bot always reports it's handle as **self.me.handle**. It doesn't look for a full name to be specified.

**self.me.id** likewise is the alphanumeric ID of the user. Full name isn't checked for.

**Comment by Chalta** [comment]
I've submitted this as a pull request to the skoczen repo as well.

**Comment by Chalta** [comment]
https://github.com/pastorhudson/pcobot/pull/74

Merged to dev.

**Comment by pastorhudson** [comment]
Merged to master
