### ISSUE TITLE
Whitelist command naive to presence of acl/whitelist

### ISSUE THREAD

**Issue by Chalta** [pastorhudson/pcobot#77]
If a restricted command is run before whitelist is initialized (by acl command), all channels are effectively whitelisted since the command returns an error *and* the requested information:

```
I might have that address.
Exception: <class 'TypeError'>
Here you go!
[address]
```

**Comment by pastorhudson** [comment]
Fixed. An admin needs to be assigned or all commands will respond as a direct message.

**Comment by Chalta** [comment]
If you want to reopen it and assign to me, I'll use this as my reminder to update readme.
